### ISSUE TITLE
`'NoneType' object has no attribute 'replace'` in tidal search

### ISSUE THREAD

**Issue by wvffle** [JuniorJPDJ/musicsearchbot#1]
So I've searched with `@bot .a drink the sea` and it seems like the bot's crashing due to the missing cover photo
![image](https://user-images.githubusercontent.com/13330620/91335915-9bb09700-e7c0-11ea-9692-85426e8260f1.png)

**Comment by JuniorJPDJ** [comment]
Have I fixed this?

**Comment by JuniorJPDJ** [comment]
And now @wvffle ?

**Comment by wvffle** [comment]
I've experienced this issue earlier this day, with the main bot we're using. You have to PM me which bot to test

**Comment by JuniorJPDJ** [comment]
fixed by e9cb240f62a16e2a462ff8b8544b741d373e80c5
